#!/bin/sh
# Write config.toml from Railway env vars before starting MPT.
# Required: MPT_PEXELS_KEY
# No LLM key needed — script is pre-generated by the pipeline and passed
# via video_script in the POST payload; MPT only handles video assembly.

PEXELS="${MPT_PEXELS_KEY:-}"

cat > /app/config.toml << TOML
[app]
video_source = "pexels"
pexels_api_keys = ["${PEXELS}"]
pixabay_api_keys = []
llm_provider = "openai"
openai_api_key = "unused"
openai_base_url = "https://openrouter.ai/api/v1"
openai_model_name = "anthropic/claude-haiku-4-5"
subtitle_provider = "edge"
max_concurrent_tasks = 3
max_queued_tasks = 20
video_codec = "libx264"
tls_verify = true

[whisper]
model_size = "large-v3"
device = "CPU"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[ui]
language = "en"
tts_server = "edge"
voice_name = "en-US-GuyNeural-Male"
font_name = "MicrosoftYaHeiBold.ttc"
subtitle_position = "bottom"
text_fore_color = "#FFFFFF"
font_size = 60
subtitle_background_enabled = true
subtitle_background_color = "#000000"
TOML

echo "[entrypoint] config.toml written (pexels_key=${PEXELS:0:8}...)"
exec python main.py
